a = int(input("Введите первое число:"))
b = int(input("Введите второе число:"))
print(f"Число A: {a}")
print(f"Число B: {b}")
print(f"{a} == {b}: {a == b}")
print(f"{a} != {b}: {a != b}")
print(f"{a} > {b}: {a > b}")
print(f"{a} < {b}: {a < b}")
print(f"{a} >= {b}: {a >= b}")
print(f"{a} <= {b}: {a <=b}")
