name = input("Как тебя зовут?")
year_born = int(input("Год рождения?"))
year = int(input("Какой сейчас год?"))
age = (year - year_born)
height_m = float(input("Рост в метрах?"))
height_sm = (height_m * 100)
print("=== Мой профиль ===")
print(f"Имя: {name}")
print(f"Год рождения: {year_born}")
print(f"Возраст: {age}")
print(f"Рост: {height_sm} см")
print("=====================")
